(function(){
'use strict';
const key=()=>ProjectAccess.user.uid+'|hamburg-project';
async function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('drawing-local-library',1);r.onupgradeneeded=()=>r.result.createObjectStore('folders');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function folder(save,kind=''){const d=await db();try{return await new Promise((resolve,reject)=>{const t=d.transaction('folders',save?'readwrite':'readonly'),s=t.objectStore('folders'),r=save?s.put(save,key()+kind):s.get(key()+kind);let value;r.onsuccess=()=>value=r.result;t.oncomplete=()=>resolve(save||value);t.onerror=()=>reject(t.error)})}finally{d.close()}}
const fileName=(name,sha)=>'drawing-'+String(name).replace(/\.pdf$/i,'').replace(/[^\w .-]/g,'_').slice(0,100)+'-'+sha.slice(0,16)+'.pdf';
async function digest(file){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function pick(){if(!window.showDirectoryPicker)throw Error('Folder access is unavailable in this browser. Local PDFs can still be selected when opening a drawing.');const h=await showDirectoryPicker({mode:'readwrite',id:'drawing-library'});await folder(h);return h.name}
async function save(file,sha){const h=await folder();if(!h)return {copied:false};if(await h.queryPermission({mode:'readwrite'})!=='granted')throw Error('Click Choose local folder to grant access again, then publish.');const name=fileName(file.name,sha);try{const existing=await(await h.getFileHandle(name)).getFile();if(await digest(existing)!==sha)throw Error('A different local PDF has this name. Choose another folder.');return {copied:true}}catch(e){if(e.name!=='NotFoundError')throw e}const handle=await h.getFileHandle(name,{create:true}),writer=await handle.createWritable();try{await writer.write(file);await writer.close()}catch(e){await writer.abort().catch(()=>{});throw e}return {copied:true}}
const libraries=new Map(),catalogs=new Map();
const nameKey=s=>String(s||'').normalize('NFC').toLowerCase();
function alive(signal){if(signal?.aborted)throw new DOMException('Viewer closed','AbortError')}
async function library(){const id=key();if(!libraries.has(id))libraries.set(id,await folder(undefined,':lookup'));return libraries.get(id)}
async function pickLibrary(){if(!window.showDirectoryPicker)throw Error('Choose a drawing folder in Chrome or Edge. You can also select an individual PDF below.');const h=await showDirectoryPicker({mode:'read',id:'drawing-source-library'});await folder(h,':lookup');libraries.set(key(),h);catalogs.delete(key());return h.name}
async function scan(h,signal,progress){const map=new Map(),pending=[h];let count=0,visited=0;while(pending.length){alive(signal);const dir=pending.pop();for await(const entry of dir.values()){alive(signal);if(entry.kind==='directory')pending.push(entry);else if(/\.pdf$/i.test(entry.name)){const name=nameKey(entry.name);if(!map.has(name))map.set(name,[]);map.get(name).push(entry);count++}if(++visited%100===0){progress?.('Finding local PDFs… '+count);await new Promise(r=>setTimeout(r,0))}}}catalogs.set(key(),map);return map}
async function matching(map,meta,signal,progress){const names=new Set([nameKey(String(meta.fileName||meta.path).split(/[\\/]/).pop()),nameKey(fileName(meta.fileName,meta.sha))]);for(const name of names)for(const handle of map.get(name)||[]){alive(signal);progress?.('Checking PDF revision: '+handle.name);let file;try{file=await handle.getFile()}catch(e){if(e.name==='NotFoundError')continue;throw e}if(await digest(file)===meta.sha){alive(signal);return file}}return null}
async function read(meta,signal,progress,refresh=false){alive(signal);const h=await library();if(h&&await h.queryPermission({mode:'read'})==='granted'){
 const cached=!refresh&&catalogs.get(key());const map=cached||await scan(h,signal,progress);const found=await matching(map,meta,signal,progress);if(found)return found;
 if(cached){const fresh=await scan(h,signal,progress),retry=await matching(fresh,meta,signal,progress);if(retry)return retry}
 }
 // Keep libraries created by v0.25.0 usable as well.
 const saved=await folder();if(saved&&await saved.queryPermission({mode:'read'})==='granted'){try{const file=await(await saved.getFileHandle(fileName(meta.fileName,meta.sha))).getFile();if(await digest(file)===meta.sha)return file}catch(e){if(e.name!=='NotFoundError')throw e}}return null;
}
function choose(meta,container,signal){return new Promise((resolve,reject)=>{const wrap=document.createElement('div');wrap.className='drawing-local-picker';const label=document.createElement('p');label.textContent='Choose the drawings folder once on this computer. Subfolders are included; PDFs are matched by filename and checked against the indexed revision.';const message=document.createElement('p');message.setAttribute('role','status');message.textContent='Looking for: '+meta.fileName;
 const select=document.createElement('button');select.type='button';select.textContent='Choose drawings folder';
 const retry=document.createElement('button');retry.type='button';retry.textContent='Allow access / search again';
 const input=document.createElement('input');input.type='file';input.accept='.pdf,application/pdf';input.setAttribute('aria-label','Select local drawing PDF');const alternative=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Or select one PDF';alternative.append(summary,input);wrap.append(label,select,retry,message,alternative);container.append(wrap);
 let finished=false;const abort=()=>{if(finished)return;finished=true;wrap.remove();reject(new DOMException('Viewer closed','AbortError'))};const done=file=>{if(finished)return;finished=true;signal?.removeEventListener('abort',abort);wrap.remove();resolve(file)};signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted){abort();return}
 async function find(action){select.disabled=retry.disabled=true;try{await action();alive(signal);const file=await read(meta,signal,text=>message.textContent=text,true);if(file)done(file);else message.textContent='No matching revision found for '+meta.fileName+'. Check the folder or select the indexed PDF.'}catch(e){if(e.name!=='AbortError')message.textContent=e.message}finally{select.disabled=retry.disabled=false}}
 select.onclick=()=>find(pickLibrary);retry.onclick=()=>find(async()=>{const h=libraries.get(key());if(!h)throw Error('Choose drawings folder first.');if(await h.requestPermission({mode:'read'})!=='granted')throw Error('Folder access was not granted.');});
 input.onchange=()=>{const file=input.files[0];if(file)done(file)};
})}
window.DrawingLocal={pick,save,read,choose,digest,pickLibrary};
if(/\/search\.html$/.test(location.pathname))ProjectAccess.ready.then(()=>{const host=document.querySelector('.mode-tabs');if(!host)return;const button=document.createElement('button');button.type='button';button.textContent='Local drawings folder';button.title='Choose the folder containing your PDFs and subfolders';button.onclick=async()=>{try{const name=await pickLibrary();button.textContent='Drawing folder: '+name;button.title='Change local drawing folder'}catch(e){if(e.name!=='AbortError'){button.title=e.message;button.textContent='Folder unavailable — try Chrome / Edge'}}};host.append(button)});
})();
