(function(){
'use strict';
const API='https://drawing-finder-ocr-api-639231007303.europe-west1.run.app';let libraries;
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('PDF viewer files could not be loaded. Check vendor/pdf.'))};document.head.append(s)})}
async function deps(){if(!libraries)libraries=(async()=>{if(!window.pdfjsLib)await script('vendor/pdf/pdf.min.js?v=0.24.0');pdfjsLib.GlobalWorkerOptions.workerSrc='vendor/pdf/pdf.worker.min.js?v=0.24.0';if(!window.PDFLib)await script('vendor/pdf/pdf-lib.min.js?v=0.24.0')})().catch(e=>{libraries=null;throw e});return libraries}
async function exportPdf(bytes,doc,occurrences){
 const out=await PDFLib.PDFDocument.load(bytes),pages=out.getPages();
 for(const o of occurrences){const page=await doc.getPage(o.page),vp=page.getViewport({scale:1});for(const b of o.boxes){const corners=[[b.x0,b.y0],[b.x1,b.y0],[b.x1,b.y1],[b.x0,b.y1]].map(([x,y])=>vp.convertToPdfPoint(x*vp.width,y*vp.height));const xs=corners.map(p=>p[0]),ys=corners.map(p=>p[1]);pages[o.page-1].drawRectangle({x:Math.min(...xs)-2,y:Math.min(...ys)-2,width:Math.max(...xs)-Math.min(...xs)+4,height:Math.max(...ys)-Math.min(...ys)+4,color:PDFLib.rgb(1,.86,0),opacity:.38,borderColor:PDFLib.rgb(.95,.27,0),borderWidth:2,borderOpacity:1})}}
 return out.save();
}
async function open(path,input){
 const tags=[...new Set((Array.isArray(input)?input:[input]).map(v=>String(v||'').trim()).filter(Boolean))];if(!tags.length)return;
 const previous=document.getElementById('drawingViewer');if(previous?.open)previous.close();
 const dialog=document.createElement('dialog');dialog.id='drawingViewer';dialog.className='drawing-viewer';
 dialog.innerHTML='<header><strong></strong><button data-action="close">Close ×</button></header><nav><button data-action="previous">‹ Page</button><span class="dv-page"></span><button data-action="next">Page ›</button><button data-action="minus" aria-label="Zoom out">−</button><button data-action="plus" aria-label="Zoom in">+</button><button data-action="match">Next match</button><button data-action="download">Download highlighted PDF</button></nav><p class="dv-status" role="status">Loading private drawing…</p><div class="dv-scroll"><div class="dv-sheet"><canvas></canvas><div class="dv-marks"></div></div></div>';
 dialog.querySelector('strong').textContent=path+' · '+tags.length+' tag(s)';document.body.append(dialog);dialog.showModal();
 const status=dialog.querySelector('.dv-status'),sheet=dialog.querySelector('.dv-sheet'),canvas=dialog.querySelector('canvas'),marks=dialog.querySelector('.dv-marks'),button=name=>dialog.querySelector('[data-action="'+name+'"]');
 let doc,bytes,data,pageNumber=1,zoom=1,matchIndex=0,task,loadingTask,closed=false,renderChain=Promise.resolve(),serial=0;const controller=new AbortController();
 button('close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{closed=true;serial++;controller.abort();task?.cancel();loadingTask?.destroy();doc?.destroy();canvas.width=canvas.height=1;bytes=null;dialog.remove()},{once:true});
 function render(focus){const request=++serial;renderChain=renderChain.catch(()=>{}).then(async()=>{if(closed||request!==serial)return;const page=await doc.getPage(pageNumber);if(closed||request!==serial)return;const base=page.getViewport({scale:1}),width=Math.max(280,dialog.clientWidth-55),scale=width/base.width*zoom,vp=page.getViewport({scale});const dpr=Math.min(window.devicePixelRatio||1,2,Math.sqrt(12000000/(vp.width*vp.height)));canvas.width=Math.ceil(vp.width*dpr);canvas.height=Math.ceil(vp.height*dpr);canvas.style.width=vp.width+'px';canvas.style.height=vp.height+'px';sheet.style.width=vp.width+'px';sheet.style.height=vp.height+'px';marks.replaceChildren();task=page.render({canvasContext:canvas.getContext('2d'),viewport:vp,transform:[dpr,0,0,dpr,0,0]});await task.promise;
  if(closed||request!==serial)return;for(const [i,o] of data.occurrences.entries()){if(o.page!==pageNumber)continue;for(const b of o.boxes){const mark=document.createElement('span');mark.className='dv-mark'+(i===focus?' selected':'');mark.style.cssText=`left:${b.x0*100}%;top:${b.y0*100}%;width:${(b.x1-b.x0)*100}%;height:${(b.y1-b.y0)*100}%`;mark.dataset.tag=o.tag;mark.title=o.tag+' · '+o.source;marks.append(mark)}}dialog.querySelector('.dv-page').textContent=pageNumber+' / '+doc.numPages;button('previous').disabled=pageNumber===1;button('next').disabled=pageNumber===doc.numPages;if(focus!==undefined)marks.querySelector('.selected')?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'});
 }).catch(e=>{if(!closed&&e.name!=='RenderingCancelledException')status.textContent=e.message});return renderChain}
 for(const b of dialog.querySelectorAll('nav button'))b.disabled=true;
 try{await deps();data=await ProjectAccess.api('/api/public/drawing-highlight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,tags})});if(closed)return;if(data.storage==='local'){status.textContent='Opening local PDF…';let local;try{local=await DrawingLocal.read(data,controller.signal,text=>status.textContent=text)}catch(e){if(closed)throw e;status.textContent=e.message}const file=local||await DrawingLocal.choose(data,dialog.querySelector('.dv-scroll'),controller.signal);bytes=new Uint8Array(await file.arrayBuffer())}else{const response=await fetch(API+'/api/public/drawing-pdf?'+new URLSearchParams({path,sha:data.sha}),{signal:controller.signal});if(!response.ok)throw Error('Drawing unavailable or updated. Close and reopen it.');bytes=new Uint8Array(await response.arrayBuffer())}const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');if(digest!==data.sha)throw Error('PDF revision does not match its positions. Close and select the indexed PDF, or re-import the new revision.');if(closed)return;
  loadingTask=pdfjsLib.getDocument({data:bytes.slice(),isEvalSupported:false});doc=await loadingTask.promise;if(closed)return;
  data.occurrences=data.occurrences.filter(o=>o.page<=doc.numPages);pageNumber=data.occurrences[0]?.page||1;dialog.querySelector('strong').textContent=data.fileName+' · '+tags.length+' tag(s)';const norm=v=>String(v).toUpperCase().replace(/\s+/g,'').replace(/[•·:]/g,'-'),located=new Set(data.occurrences.map(o=>norm(o.tag))),missing=tags.filter(t=>!located.has(norm(t)));status.textContent=located.size+' / '+tags.length+' tags highlighted · '+data.occurrences.length+' occurrences.'+(missing.length?' Missing saved positions: '+missing.slice(0,12).join(', ')+(missing.length>12?' and '+(missing.length-12)+' more':'')+'. Re-import the PDF to capture them.':'')+' Check OCR marks against the drawing.';
  for(const b of dialog.querySelectorAll('nav button'))b.disabled=false;button('match').disabled=button('download').disabled=!data.occurrences.length;
  button('previous').onclick=()=>{if(pageNumber>1){pageNumber--;render()}};button('next').onclick=()=>{if(pageNumber<doc.numPages){pageNumber++;render()}};button('plus').onclick=()=>{zoom=Math.min(6,zoom*1.4);render()};button('minus').onclick=()=>{zoom=Math.max(.5,zoom/1.4);render()};button('match').onclick=()=>{matchIndex=(matchIndex+1)%data.occurrences.length;pageNumber=data.occurrences[matchIndex].page;render(matchIndex)};
  button('download').onclick=async()=>{button('download').disabled=true;try{const saved=await exportPdf(bytes,doc,data.occurrences);if(closed)return;const url=URL.createObjectURL(new Blob([saved],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=data.fileName.replace(/\.pdf$/i,'')+'-'+(tags.length>1?tags.length+'-tags':tags[0].replace(/[^a-z0-9-]/gi,'_'))+'-highlighted.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){if(!closed)status.textContent='Export failed: '+e.message}finally{if(!closed)button('download').disabled=false}};
  await render(0);
 }catch(e){if(!closed)status.textContent=e.message}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-highlight-path]');if(b){let tags;try{tags=b.dataset.highlightTags?JSON.parse(b.dataset.highlightTags):b.dataset.highlightTag}catch{return}open(b.dataset.highlightPath,tags)}});
window.DrawingViewer={open,exportPdf};
})();
