(function(){
'use strict';
async function create({dialog,sheet,marks,button,doc,sha,page}){
 const key='annotations-v1:'+sha;let annotations=[];try{annotations=await DrawingCache.get(key)||[]}catch{}
 const scroll=dialog.querySelector('.dv-scroll'),layer=document.createElement('div'),hint=document.createElement('small');layer.className='dv-annotations';sheet.append(layer);hint.className='dv-edit-status';hint.textContent='Drag to pan · Annotations are saved on this browser; download a PDF copy to share.';dialog.querySelector('nav').after(hint);
 let mode='pan',drag=null,preview=null,queue=Promise.resolve(),disposed=false;
 function save(){const copy=structuredClone(annotations);queue=queue.catch(()=>{}).then(()=>DrawingCache.put(key,copy)).catch(()=>{if(!disposed)hint.textContent='Local save failed. Download your annotated PDF before closing.'})}
 function mark(a){const el=document.createElement('span');el.className='dv-annotation '+(a.type==='text'?'dv-note':'dv-area');el.style.cssText=`left:${a.x0*100}%;top:${a.y0*100}%;width:${(a.x1-a.x0)*100}%;height:${(a.y1-a.y0)*100}%`;if(a.type==='text'){el.textContent=a.text;el.style.fontSize=(a.y1-a.y0)*sheet.clientHeight*.75+'px'}layer.append(el);return el}
 function paint(){layer.replaceChildren();annotations.filter(a=>a.page===page()).forEach(mark);button('undo').disabled=!annotations.length}
 function setMode(next){mode=next;scroll.dataset.tool=mode;for(const k of ['pan','area','text'])button(k).setAttribute('aria-pressed',String(k===mode))}
 for(const k of ['pan','area','text'])button(k).onclick=()=>setMode(k);
 button('undo').onclick=()=>{annotations.pop();save();paint()};setMode('pan');
 function point(e){const r=sheet.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
 function down(e){if(e.button!==0||!sheet.contains(e.target))return;e.preventDefault();const p=point(e);if(mode==='text'){const text=prompt('Text to add to this PDF (max 200 characters):');if(!text?.trim())return;const value=text.trim().slice(0,200),height=.016,width=Math.min(.55,Math.max(.08,value.length*.008));annotations.push({type:'text',text:value,page:page(),x0:Math.min(p.x,1-width),y0:Math.min(p.y,1-height),x1:Math.min(p.x+width,1),y1:Math.min(p.y+height,1)});save();paint();return}drag={x:e.clientX,y:e.clientY,left:scroll.scrollLeft,top:scroll.scrollTop,p,page:page(),mode};scroll.setPointerCapture(e.pointerId);if(mode==='area')preview=mark({type:'area',x0:p.x,y0:p.y,x1:p.x,y1:p.y})}
 function move(e){if(!drag)return;if(drag.mode==='pan'){scroll.scrollLeft=drag.left-(e.clientX-drag.x);scroll.scrollTop=drag.top-(e.clientY-drag.y)}else{const p=point(e),b={x0:Math.min(p.x,drag.p.x),y0:Math.min(p.y,drag.p.y),x1:Math.max(p.x,drag.p.x),y1:Math.max(p.y,drag.p.y)};preview.style.left=b.x0*100+'%';preview.style.top=b.y0*100+'%';preview.style.width=(b.x1-b.x0)*100+'%';preview.style.height=(b.y1-b.y0)*100+'%'}}
 function up(e){if(!drag)return;const old=drag;drag=null;if(scroll.hasPointerCapture(e.pointerId))scroll.releasePointerCapture(e.pointerId);if(old.mode==='area'&&e.type!=='pointercancel'&&old.page===page()){const p=point(e),a={type:'area',page:page(),x0:Math.min(p.x,old.p.x),y0:Math.min(p.y,old.p.y),x1:Math.max(p.x,old.p.x),y1:Math.max(p.y,old.p.y)};if(a.x1-a.x0>.001&&a.y1-a.y0>.001){annotations.push(a);save()}}preview=null;paint()}
 scroll.addEventListener('pointerdown',down);scroll.addEventListener('pointermove',move);scroll.addEventListener('pointerup',up);scroll.addEventListener('pointercancel',up);
 return {annotations,paint,destroy(){disposed=true;scroll.removeEventListener('pointerdown',down);scroll.removeEventListener('pointermove',move);scroll.removeEventListener('pointerup',up);scroll.removeEventListener('pointercancel',up)}};
}
async function exportAnnotations(out,doc,annotations){for(const a of annotations){const p=await doc.getPage(a.page),vp=p.getViewport({scale:1}),bl=vp.convertToPdfPoint(a.x0*vp.width,a.y1*vp.height),br=vp.convertToPdfPoint(a.x1*vp.width,a.y1*vp.height),tl=vp.convertToPdfPoint(a.x0*vp.width,a.y0*vp.height),width=Math.hypot(br[0]-bl[0],br[1]-bl[1]),height=Math.hypot(tl[0]-bl[0],tl[1]-bl[1]),rotate=PDFLib.degrees(Math.atan2(br[1]-bl[1],br[0]-bl[0])*180/Math.PI),page=out.getPages()[a.page-1];if(a.type==='area'){page.drawRectangle({x:bl[0],y:bl[1],width,height,rotate,color:PDFLib.rgb(1,.88,0),opacity:.3,borderColor:PDFLib.rgb(.95,.65,0),borderWidth:1})}else{const c=document.createElement('canvas');c.height=64;c.width=Math.max(64,Math.min(4096,Math.round(64*width/height)));const ctx=c.getContext('2d');ctx.fillStyle='#fff8cc';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#233c4b';ctx.font='48px sans-serif';ctx.textBaseline='middle';ctx.fillText(a.text,4,32,c.width-8);const image=await out.embedPng(c.toDataURL('image/png'));page.drawImage(image,{x:bl[0],y:bl[1],width,height,rotate});c.width=c.height=1}}}
window.DrawingEditor={create,exportAnnotations};
})();
