(function(){
'use strict';
const main=document.querySelector('main');main.classList.add('indexing-workspace');
const title=main.querySelector('h1');title.textContent='Drawing Index';
const subtitle=title.nextElementSibling;subtitle.textContent='Add drawings, check the detected tags and publish them to your project.';
const hero=document.createElement('header');hero.className='indexer-hero';title.before(hero);hero.innerHTML='<div class="indexer-eyebrow">PROJECT DOCUMENTS · v0.29.0</div>';hero.append(title,subtitle);const back=document.createElement('a');back.href='search.html';back.className='indexer-back';back.textContent='← Back to search';hero.append(back);
const originalNote=hero.nextElementSibling;if(originalNote?.classList.contains('note'))originalNote.hidden=true;
const report=document.getElementById('truncatedPipelineReport');if(report)report.hidden=true;
const importer=document.getElementById('drawingImport');hero.after(importer);importer.querySelector('h2').textContent='1. Add drawings';importer.querySelector('p').textContent='PDF, DWG or ZIP. PDF scans keep tag positions for highlighting. Nothing is published until you choose Publish to project.';
const actions=importer.querySelector('.drawing-import-actions'),file=document.getElementById('drawingFiles'),picker=document.createElement('label');picker.className='drawing-picker';picker.innerHTML='<strong>Choose your drawings</strong><span>Select files / ZIP, or use Choose drawing folder to include subfolders.</span>';actions.before(picker);picker.append(file,document.getElementById('drawingFolder'));
const settings=document.createElement('div');settings.className='drawing-scan-settings';settings.innerHTML='<label>Drawing type<select id="drawingScanMode"><option value="layout">Drawing / electrical layout — recommended</option><option value="table">Structured instrument / valve table</option></select></label><label>OCR detail<select id="drawingLayoutDpi"><option value="300">Standard · 300 DPI</option><option value="400" selected>Fine labels · 400 DPI</option><option value="500">Very small labels · 500 DPI (slower)</option></select></label><p>Drawing mode scans the full page without requiring a table header. Short cabinet codes require a KKS column or an exact cable-list match. OCR readings remain marked for review.</p>';picker.after(settings);
const force=document.getElementById('drawingForceOCR').closest('label');force.classList.add('drawing-force');settings.after(force);
const scrolls=importer.querySelectorAll('.drawing-import-scroll');for(const [i,scroll] of [...scrolls].entries()){const h=document.createElement('h3');h.id=i?'drawingReviewHeading':'drawingProgressHeading';h.textContent=i?'3. Review and publish':'2. Scan progress';scroll.before(h)}
const storage=document.createElement('div');storage.className='drawing-storage-options';storage.innerHTML='<label>PDF storage<select id="drawingStorageMode"><option value="local">Local PDF — recommended</option><option value="cloud">Cloud PDF — optional</option></select></label><button type="button" id="drawingLocalFolder">Choose local folder</button><p id="drawingLocalInfo">The PDF stays on your computer. Optionally choose a folder to save a local copy and reopen it automatically. Without a folder, select the original PDF when viewing. Tags and positions are always stored in the database.</p>';scrolls[1].before(storage);
document.getElementById('drawingLocalFolder').onclick=async()=>{try{document.getElementById('drawingLocalInfo').textContent='Local library: '+await DrawingLocal.pick()}catch(e){if(e.name!=='AbortError')document.getElementById('drawingLocalInfo').textContent=e.message}};
document.getElementById('drawingStorageMode').onchange=e=>{document.getElementById('drawingLocalFolder').hidden=e.target.value==='cloud';document.getElementById('drawingLocalInfo').textContent=e.target.value==='cloud'?'Original PDF will be uploaded to private cloud storage (25 MB limit).':'PDF stays local. On another computer you will need to select the same PDF; its revision is checked before highlighting.'};
const publish=document.createElement('div');publish.className='drawing-publish-actions';scrolls[1].before(publish);publish.append(document.getElementById('drawingExport'),document.getElementById('drawingPublish'));
document.getElementById('drawingStart').textContent='Scan drawings';document.getElementById('drawingPublish').textContent='Publish to project';
const hint=document.createElement('p');hint.className='indexer-hint';hint.textContent='OCR readings are candidates, not dual-engine verified values. Check short codes, crossed-out rows and revisions before publishing.';scrolls[1].after(hint);
function fold(node,label,description){if(!node)return;const d=document.createElement('details');d.className='indexer-advanced';const summary=document.createElement('summary');summary.textContent=label;node.before(d);d.append(summary);const p=document.createElement('p');p.textContent=description;d.append(p,node)}
fold(document.getElementById('projectIndexer'),'Folder indexing','Existing folder checkpoints and structured-table tools. Use Add drawings → Choose drawing folder for the current tag, cable-list validation and highlight workflow.');
fold(document.getElementById('cloudIndex'),'Project connection and cloud index','Check the connection or manage existing cloud records.');
const grid=[...main.children].find(e=>e.classList.contains('grid'));fold(grid,'Advanced tools · manual zones and table analysis','Keep the existing table extraction tools for row, pipeline and elevation relationships. Manual zones are optional; they are not required in Drawing mode.');
const secret=document.getElementById('cloudAccessKey')?.closest('.secret-row');if(secret){if(secret.previousElementSibling?.tagName==='LABEL')secret.previousElementSibling.hidden=true;secret.hidden=true}
document.getElementById('runDual').textContent='Scan selected regions';
})();
