(function(){
'use strict';
const key=()=>ProjectAccess.user.uid+'|hamburg-project';
async function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('drawing-local-library',1);r.onupgradeneeded=()=>r.result.createObjectStore('folders');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function folder(save){const d=await db();try{return await new Promise((resolve,reject)=>{const t=d.transaction('folders',save?'readwrite':'readonly'),s=t.objectStore('folders'),r=save?s.put(save,key()):s.get(key());let value;r.onsuccess=()=>value=r.result;t.oncomplete=()=>resolve(save||value);t.onerror=()=>reject(t.error)})}finally{d.close()}}
const fileName=(name,sha)=>'drawing-'+String(name).replace(/\.pdf$/i,'').replace(/[^\w .-]/g,'_').slice(0,100)+'-'+sha.slice(0,16)+'.pdf';
async function digest(file){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function pick(){if(!window.showDirectoryPicker)throw Error('Folder access is unavailable in this browser. Local PDFs can still be selected when opening a drawing.');const h=await showDirectoryPicker({mode:'readwrite',id:'drawing-library'});await folder(h);return h.name}
async function save(file,sha){const h=await folder();if(!h)return {copied:false};if(await h.queryPermission({mode:'readwrite'})!=='granted')throw Error('Click Choose local folder to grant access again, then publish.');const name=fileName(file.name,sha);try{const existing=await(await h.getFileHandle(name)).getFile();if(await digest(existing)!==sha)throw Error('A different local PDF has this name. Choose another folder.');return {copied:true}}catch(e){if(e.name!=='NotFoundError')throw e}const handle=await h.getFileHandle(name,{create:true}),writer=await handle.createWritable();try{await writer.write(file);await writer.close()}catch(e){await writer.abort().catch(()=>{});throw e}return {copied:true}}
async function read(meta){try{const h=await folder();if(h&&await h.queryPermission({mode:'read'})==='granted')return await(await h.getFileHandle(fileName(meta.fileName,meta.sha))).getFile()}catch{}return null}
function choose(meta,container,signal){return new Promise((resolve,reject)=>{const wrap=document.createElement('div');wrap.className='drawing-local-picker';const label=document.createElement('p');label.textContent='This PDF is stored locally. Select '+meta.fileName+' to open its saved highlights.';const input=document.createElement('input');input.type='file';input.accept='.pdf,application/pdf';input.setAttribute('aria-label','Select local drawing PDF');wrap.append(label,input);container.append(wrap);const abort=()=>{wrap.remove();reject(new DOMException('Viewer closed','AbortError'))};signal?.addEventListener('abort',abort,{once:true});input.onchange=()=>{const file=input.files[0];if(file){signal?.removeEventListener('abort',abort);wrap.remove();resolve(file)}}})}
window.DrawingLocal={pick,save,read,choose,digest};
})();
