(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),key=s=>String(s||'').trim().toUpperCase();
function summarize(packages,punches){const subsystems=new Set(packages.map(r=>key(r.subsystem))),numbers=new Set(packages.map(r=>key(r.package)));const rows=punches.filter(r=>{const p=r.fields?.find(f=>/^toppackage(?:number|no)?$/i.test(String(f.label).replace(/[^a-z]/gi,'')))?.value;return p?numbers.has(key(p)):subsystems.has(key(r.subsystem))});const categories=['A','B','C'].map(category=>{const list=rows.filter(r=>key(r.category)===category),closed=list.filter(r=>PunchItems.rowStatus(r).status==='Closed').length;return {category,total:list.length,closed,remaining:list.length-closed}});const disciplines=new Map();for(const r of rows){const name=PunchItems.discipline(r)||'Unspecified';if(!disciplines.has(name))disciplines.set(name,{name,total:0,closed:0});const d=disciplines.get(name);d.total++;if(PunchItems.rowStatus(r).status==='Closed')d.closed++}return {total:packages.length,done:packages.filter(r=>r.handedOver).length,walkdown:packages.filter(r=>r.walkdownComplete===true).length,walkdownUnknown:packages.filter(r=>r.walkdownComplete==null).length,rows,categories,disciplines:[...disciplines.values()].sort((a,b)=>a.name.localeCompare(b.name))}}
const host=document.createElement('section');host.id='handoverStatus';host.hidden=true;document.getElementById('punchDashboard').after(host);let active=false,data=null,busy=false;
host.innerHTML=`<header class="handover-heading"><div><span class="eyebrow">PROJECT HANDOVER</span><h2>Handed Over to Commissioning</h2></div><div><span class="handover-updated"></span><button class="action" data-refresh>Refresh status</button></div></header><div class="handover-filters"><label>Subsystem / description<input type="search" data-query placeholder="Find subsystem or description…"></label><label>TOP package<input type="search" data-package placeholder="Package number…"></label><label>Handover<select data-filter="handedOver"><option value="">All packages</option><option value="true">Handed over</option><option value="false">Pending handover</option></select></label><label>Walkdown<select data-filter="walkdownComplete"><option value="">All</option><option value="true">Done</option><option value="false">Not done</option></select></label><button class="action" data-clear>Clear filters</button><details class="handover-extra"><summary>More filters</summary><div>${[['gas','Gas subsystem'],['backfeed','Backfeed'],['currentFlow','Current flow'],['firstFire','First fire'],['priority','Monthly priority'],['protocol','Completion protocol']].map(([k,l])=>'<label>'+l+'<select data-filter="'+k+'"><option value="">All</option></select></label>').join('')}</div></details></div><p class="handover-message" role="status"></p><div class="handover-content"><div class="handover-overview"></div><div class="handover-punch"><h3>Punch status <small>in selected TOP packages</small></h3><div class="handover-categories"></div></div><div class="handover-bottom"><article><h3>Punches by discipline</h3><div class="handover-disciplines"></div></article><article><h3>TOP package status</h3><div class="handover-packages"></div></article></div><p class="handover-note">Current workbook snapshot. Handover = “Done” in TOP → Handed over to CSU. Walkdown = “done” in SYSTEM WALKDOWN. Blank handover values remain pending.</p></div>`;
function filters(){const query=key(host.querySelector('[data-query]').value),pkg=key(host.querySelector('[data-package]').value);return (data?.rows||[]).filter(r=>(!query||key(r.subsystem+' '+r.description).includes(query))&&(!pkg||key(r.package).includes(pkg))&&[...host.querySelectorAll('[data-filter]')].every(e=>!e.value||(e.value==='__blank'?!String(r[e.dataset.filter]??'').trim():String(r[e.dataset.filter])===e.value)))}
function render(){if(!active)return;const message=host.querySelector('.handover-message'),content=host.querySelector('.handover-content');content.hidden=!data?.available;if(!data?.available){message.textContent=data?.reason||'Loading TOP package status…';return}const packages=filters(),snapshot=PunchItems.getSnapshot(),a=summarize(packages,snapshot?.rows||[]);host.querySelector('.handover-punch').hidden=!snapshot;message.textContent=packages.length+' / '+data.rows.length+' TOP packages'+(!snapshot?' · Punch data not available':data.stale?' · Source update overdue; showing saved snapshot':'');
const card=(title,total,done,note,cls)=>{const pct=total?done/total*100:0;return '<article class="handover-kpi '+cls+'"><div><h3>'+title+'</h3><p>'+note+'</p><div class="handover-numbers"><span><strong>'+total+'</strong>Total</span><span><strong>'+done+'</strong>Completed</span><span><strong>'+(total-done)+'</strong>Remaining</span></div></div><div class="handover-ring" style="--pct:'+pct+'%"><span>'+pct.toFixed(0)+'%<small>complete</small></span></div></article>'};
host.querySelector('.handover-overview').innerHTML=card('Commissioning handover',a.total,a.done,'Turnover packages · CSU','handover-green')+card('System walkdown',a.total,a.walkdown,a.walkdownUnknown?a.walkdownUnknown+' packages have no walkdown column available':'Completed inspections','handover-blue');
host.querySelector('.handover-categories').innerHTML=a.categories.map(c=>'<article><span class="category-label">Category '+c.category+'</span><div class="handover-numbers"><span><strong>'+c.total+'</strong>Total</span><span><strong>'+c.closed+'</strong>Closed</span><span><strong>'+c.remaining+'</strong>Remaining</span></div><progress value="'+c.closed+'" max="'+Math.max(1,c.total)+'"></progress></article>').join('');
host.querySelector('.handover-disciplines').innerHTML='<table><thead><tr><th>Discipline</th><th>Total</th><th>Closed</th><th>Remaining</th></tr></thead><tbody>'+a.disciplines.map(d=>'<tr><td>'+esc(d.name)+'</td><td>'+d.total+'</td><td>'+d.closed+'</td><td>'+(d.total-d.closed)+'</td></tr>').join('')+'</tbody></table><p class="hint">'+a.rows.length+' punches in this selection'+(a.rows.length-a.categories.reduce((n,c)=>n+c.total,0)?' · '+(a.rows.length-a.categories.reduce((n,c)=>n+c.total,0))+' outside categories A/B/C':'')+'</p>';
if(!snapshot)host.querySelector('.handover-disciplines').textContent='Punch data is not available yet.';
host.querySelector('.handover-packages').innerHTML=packages.map(r=>'<div><strong>'+esc(r.subsystem)+'</strong><span class="handover-badge '+(r.handedOver?'done':'')+'">'+(r.handedOver?'Handed over':'Pending')+'</span><p>'+esc(r.description)+'</p><small>'+esc(r.package)+'</small></div>').join('')||'<p>No matching packages.</p>';
}
async function load(){if(busy)return;busy=true;const b=host.querySelector('[data-refresh]');b.disabled=true;try{const incoming=await ProjectAccess.api('/api/public/handover');data=incoming;host.querySelector('.handover-updated').textContent=incoming.syncedAt?'Last import: '+PunchItems.formatObserved(incoming.syncedAt):'';for(const s of host.querySelectorAll('.handover-extra select')){const selected=s.value,k=s.dataset.filter;s.innerHTML='<option value="">All</option>'+[...new Set((data.rows||[]).map(r=>r[k]||''))].sort().map(v=>'<option value="'+esc(v||'__blank')+'">'+esc(v||'(Blank)')+'</option>').join('');s.value=selected}render()}catch(e){host.querySelector('.handover-message').textContent='Could not refresh handover status: '+e.message}finally{busy=false;b.disabled=false}}
let timer;host.addEventListener('input',e=>{if(e.target.matches('input')){clearTimeout(timer);timer=setTimeout(render,120)}});host.addEventListener('change',render);host.querySelector('[data-clear]').onclick=()=>{host.querySelectorAll('input,select').forEach(e=>e.value='');render()};host.querySelector('[data-refresh]').onclick=load;document.addEventListener('punch-updated',()=>{if(active)void load()});
window.HandoverStatus={activate(on){active=on;host.hidden=!on;if(on){render();void load()}},summarize};
})();
