(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),key=s=>String(s||'').trim().toUpperCase();
function disciplineGroup(r){const name=key(PunchItems.discipline(r));return /ELECTR|I&C|E&I|INSTRUMENT/.test(name)?'E&I':/MECHAN|PIPING/.test(name)?'Mechanical':/CIVIL|ARCHITECT/.test(name)?'Civil':'Other'}
function summarize(packages,punches,group=''){const subsystems=new Set(packages.map(r=>key(r.subsystem))),numbers=new Set(packages.map(r=>key(r.package)));const rows=punches.filter(r=>!group||disciplineGroup(r)===group).filter(r=>{const p=r.fields?.find(f=>/^toppackage(?:number|no)?$/i.test(String(f.label).replace(/[^a-z]/gi,'')))?.value;return p?numbers.has(key(p)):subsystems.has(key(r.subsystem))});const categories=['A','B','C'].map(category=>{const list=rows.filter(r=>key(r.category)===category),closed=list.filter(r=>PunchItems.rowStatus(r).status==='Closed').length;return {category,total:list.length,closed,remaining:list.length-closed}});const disciplines=new Map();for(const r of rows){const name=disciplineGroup(r);if(!disciplines.has(name))disciplines.set(name,{name,total:0,closed:0});const d=disciplines.get(name);d.total++;if(PunchItems.rowStatus(r).status==='Closed')d.closed++}return {total:packages.length,done:packages.filter(r=>r.handedOver).length,walkdown:packages.filter(r=>r.walkdownComplete===true).length,walkdownUnknown:packages.filter(r=>r.walkdownComplete==null).length,rows,categories,disciplines:[...disciplines.values()].sort((a,b)=>a.name.localeCompare(b.name))}}
const host=document.createElement('section');host.id='handoverStatus';host.hidden=true;document.getElementById('punchDashboard').after(host);let active=false,data=null,busy=false,selectedSubsystem='';
host.innerHTML=`<header class="handover-heading"><div><span class="eyebrow">PROJECT HANDOVER</span><h2>Handed Over to Commissioning</h2></div><div><span class="handover-updated"></span><button class="action" data-refresh>Refresh status</button></div></header><div class="handover-filters"><div class="handover-subsystem"><span id="handoverSubsystemLabel">Subsystem</span><details data-subsystem-picker><summary aria-labelledby="handoverSubsystemLabel handoverSubsystemChoice"><span id="handoverSubsystemChoice">All subsystems</span><span aria-hidden="true">⌄</span></summary><div class="handover-subsystem-menu"><label>Find subsystem<input type="search" data-subsystem-search placeholder="Search code or description…" autocomplete="off"></label><div class="handover-subsystem-options" aria-label="Subsystem choices"></div></div></details></div><label>TOP package<select data-package aria-label="TOP package"><option value="">All TOP packages</option></select></label><label>Handover<select data-filter="handedOver"><option value="">All packages</option><option value="true">Handed over</option><option value="false">Pending handover</option></select></label><label>Walkdown<select data-filter="walkdownComplete"><option value="">All</option><option value="true">Done</option><option value="false">Not done</option></select></label><button class="action" data-clear>Clear filters</button><details class="handover-extra"><summary>More filters</summary><div>${[['gas','Gas subsystem'],['backfeed','Backfeed'],['currentFlow','Current flow'],['firstFire','First fire'],['priority','Monthly priority'],['protocol','Completion protocol']].map(([k,l])=>'<label>'+l+'<select data-filter="'+k+'"><option value="">All</option></select></label>').join('')}</div></details></div><div class="handover-scope" aria-live="polite"></div><p class="handover-message" role="status"></p><div class="handover-content"><div class="handover-overview"></div><div class="handover-punch"><div class="handover-punch-heading"><h3>Punch closure progress</h3><label>Discipline <select data-discipline><option value="">All disciplines</option><option>Civil</option><option>E&amp;I</option><option>Mechanical</option><option>Other</option></select></label></div><div class="handover-punch-total"></div><div class="handover-categories"></div></div><article class="handover-blockers"><h3>Handover blockers · Open A &amp; B punches</h3><p data-blocker-summary></p><div class="handover-blocker-list"></div></article><div class="handover-bottom"><article><h3>Punches by discipline</h3><div class="handover-disciplines"></div></article><article><h3>TOP package status</h3><div class="handover-packages"></div></article></div><p class="handover-note">Current workbook snapshot. Handover = “Done” in TOP → Handed over to CSU. Walkdown = “done” in SYSTEM WALKDOWN. Blank handover values remain pending.</p></div>`;
const picker=host.querySelector('[data-subsystem-picker]'),subSearch=host.querySelector('[data-subsystem-search]');
function subsystemOptions(){const options=new Map();for(const r of data?.rows||[]){const id=key(r.subsystem);if(!id)continue;if(!options.has(id))options.set(id,{id,description:r.description||'',count:0});options.get(id).count++}return [...options.values()].sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}))}
function drawSubsystemOptions(){const q=key(subSearch.value),options=subsystemOptions().filter(r=>key(r.id+' '+r.description).includes(q));host.querySelector('.handover-subsystem-options').innerHTML='<button type="button" data-subsystem="" aria-pressed="'+(!selectedSubsystem)+'"><strong>All subsystems</strong><small>Entire project</small></button>'+options.map(r=>'<button type="button" data-subsystem="'+esc(r.id)+'" aria-pressed="'+(selectedSubsystem===r.id)+'"><strong>'+esc(r.id)+'</strong><small>'+esc(r.description)+'</small><span>'+r.count+' TOP package'+(r.count===1?'':'s')+'</span></button>').join('')+(!options.length?'<p>No matching subsystem. Try another code or description.</p>':'')}
function drawPackageOptions(){const el=host.querySelector('[data-package]'),value=el.value;const rows=(data?.rows||[]).filter(r=>!selectedSubsystem||key(r.subsystem)===selectedSubsystem);el.innerHTML='<option value="">All TOP packages ('+rows.length+')</option>'+[...new Set(rows.map(r=>r.package))].sort().map(n=>'<option value="'+esc(n)+'">'+esc(n)+'</option>').join('');el.value=[...el.options].some(o=>o.value===value)?value:''}
function drawScope(){const option=subsystemOptions().find(r=>r.id===selectedSubsystem);host.querySelector('#handoverSubsystemChoice').textContent=selectedSubsystem||'All subsystems';host.querySelector('.handover-scope').innerHTML=selectedSubsystem?'<div><small>SELECTED SUBSYSTEM</small><strong>'+esc(selectedSubsystem)+'</strong><span>'+esc(option?.description||'Subsystem is no longer in the current snapshot')+'</span></div><button type="button" class="action" data-clear-subsystem aria-label="Clear subsystem selection">Clear ×</button>':'<div><small>PROJECT OVERVIEW</small><strong>All subsystems</strong><span>'+subsystemOptions().length+' subsystems · Select one above to see its progress</span></div>'}
function selectSubsystem(value){selectedSubsystem=value;host.querySelector('[data-package]').value='';drawPackageOptions();picker.open=false;subSearch.value='';drawSubsystemOptions();render();picker.querySelector('summary').focus()}
picker.addEventListener('toggle',()=>{if(picker.open){subSearch.value='';drawSubsystemOptions();subSearch.focus()}});
subSearch.addEventListener('input',drawSubsystemOptions);
picker.addEventListener('click',e=>{const b=e.target.closest('[data-subsystem]');if(b)selectSubsystem(b.dataset.subsystem)});
picker.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();picker.open=false;picker.querySelector('summary').focus()}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const buttons=[...picker.querySelectorAll('[data-subsystem]')],i=buttons.indexOf(document.activeElement);buttons[(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus()}});
document.addEventListener('pointerdown',e=>{if(picker.open&&!picker.contains(e.target))picker.open=false});
host.addEventListener('click',e=>{const b=e.target.closest('[data-blocker]');if(b)PunchItems.openRecord(Number(b.dataset.blocker));if(e.target.closest('[data-clear-subsystem]'))selectSubsystem('');if(e.target.closest('[data-reset-other]')){host.querySelectorAll('[data-filter],[data-package]').forEach(e=>e.value='');render()}});
function filters(){const pkg=key(host.querySelector('[data-package]').value);return (data?.rows||[]).filter(r=>(!selectedSubsystem||key(r.subsystem)===selectedSubsystem)&&(!pkg||key(r.package)===pkg)&&[...host.querySelectorAll('[data-filter]')].every(e=>!e.value||(e.value==='__blank'?!String(r[e.dataset.filter]??'').trim():String(r[e.dataset.filter])===e.value)))}
function render(){if(!active)return;drawScope();const message=host.querySelector('.handover-message'),content=host.querySelector('.handover-content');content.hidden=!data?.available;if(!data?.available){message.textContent=data?.reason||'Loading TOP package status…';return}const packages=filters(),snapshot=PunchItems.getSnapshot(),a=summarize(packages,snapshot?.rows||[],host.querySelector('[data-discipline]').value);host.querySelector('.handover-punch').hidden=!snapshot;message.textContent=packages.length+' / '+data.rows.length+' TOP packages'+(!snapshot?' · Punch data not available':data.stale?' · Source update overdue; showing saved snapshot':'');
if(!packages.length)message.innerHTML='No packages match these filters. '+(selectedSubsystem?'Selected subsystem: '+esc(selectedSubsystem)+'. ':'')+'<button type="button" class="action" data-reset-other>Clear other filters</button>';
const pct=(closed,total)=>total?(closed/total*100).toFixed(1)+'%':'—';
const ring=(closed,total)=>'<div class="handover-ring" style="--pct:'+(total?closed/total*100:0)+'%"><span>'+pct(closed,total)+'<small>'+(total?'closed':'No punches')+'</small></span></div>';
host.querySelector('.handover-overview').innerHTML='<div>Commissioning handover <strong>'+a.done+' / '+a.total+'</strong> packages handed over</div><div>System walkdown <strong>'+a.walkdown+' / '+a.total+'</strong> completed'+(a.walkdownUnknown?' · '+a.walkdownUnknown+' unknown':'')+'</div>';
const closed=a.rows.filter(r=>PunchItems.rowStatus(r).status==='Closed').length;
host.querySelector('.handover-punch-total').innerHTML='<div><small>ALL PUNCH CATEGORIES · '+esc(host.querySelector('[data-discipline]').value||'ALL DISCIPLINES')+'</small><h3>'+closed+' closed / '+a.rows.length+' total</h3><p>'+(a.rows.length-closed)+' remaining</p></div>'+ring(closed,a.rows.length);
host.querySelector('.handover-categories').innerHTML=a.categories.map(c=>'<article class="handover-category category-'+c.category+'"><div><span class="category-label">Category '+c.category+'</span><div class="handover-numbers"><span><strong>'+c.total+'</strong>Total</span><span><strong>'+c.closed+'</strong>Closed</span><span><strong>'+c.remaining+'</strong>Remaining</span></div></div>'+ring(c.closed,c.total)+'</article>').join('');
const blockers=a.rows.filter(r=>['A','B'].includes(key(r.category))&&PunchItems.rowStatus(r).status!=='Closed').sort((x,y)=>key(x.category).localeCompare(key(y.category))||String(x.itemNumber).localeCompare(String(y.itemNumber),undefined,{numeric:true}));
host.querySelector('.handover-blockers').hidden=!snapshot;
host.querySelector('[data-blocker-summary]').textContent=blockers.length+' open A/B punches in the current selection · A: '+blockers.filter(r=>key(r.category)==='A').length+' · B: '+blockers.filter(r=>key(r.category)==='B').length+'. This list does not change the recorded CSU handover status.';
host.querySelector('.handover-blocker-list').innerHTML=blockers.length?'<table><thead><tr><th>Punch item</th><th>Category</th><th>Subsystem</th><th>Discipline</th><th>Description</th></tr></thead><tbody>'+blockers.map(r=>'<tr><td><button class="action" data-blocker="'+snapshot.rows.indexOf(r)+'">↗ '+esc(r.itemNumber)+'</button></td><td><span class="blocker-category">'+esc(r.category)+'</span></td><td>'+esc(r.subsystem)+'</td><td>'+esc(disciplineGroup(r))+'</td><td>'+esc(r.description)+'</td></tr>').join('')+'</tbody></table>':'<p>No open A/B punches in this selection.</p>';
host.querySelector('.handover-disciplines').innerHTML='<table><thead><tr><th>Discipline</th><th>Total</th><th>Closed</th><th>Remaining</th><th>Progress</th></tr></thead><tbody>'+a.disciplines.map(d=>'<tr><td>'+esc(d.name)+'</td><td>'+d.total+'</td><td>'+d.closed+'</td><td>'+(d.total-d.closed)+'</td><td>'+pct(d.closed,d.total)+'</td></tr>').join('')+'</tbody></table><p class="hint">'+a.rows.length+' punches in this selection'+(a.rows.length-a.categories.reduce((n,c)=>n+c.total,0)?' · '+(a.rows.length-a.categories.reduce((n,c)=>n+c.total,0))+' outside categories A/B/C':'')+'</p>';
if(!snapshot)host.querySelector('.handover-disciplines').textContent='Punch data is not available yet.';
host.querySelector('.handover-packages').innerHTML=packages.map(r=>'<div><strong>'+esc(r.subsystem)+'</strong><span class="handover-badge '+(r.handedOver?'done':'')+'">'+(r.handedOver?'Handed over':'Pending')+'</span><p>'+esc(r.description)+'</p><small>'+esc(r.package)+'</small></div>').join('')||'<p>No matching packages.</p>';
}
async function load(){if(busy)return;busy=true;const b=host.querySelector('[data-refresh]');b.disabled=true;try{const incoming=await ProjectAccess.api('/api/public/handover');data=incoming;drawSubsystemOptions();drawPackageOptions();host.querySelector('.handover-updated').textContent=incoming.syncedAt?'Last import: '+PunchItems.formatObserved(incoming.syncedAt):'';for(const s of host.querySelectorAll('.handover-extra select')){const selected=s.value,k=s.dataset.filter;s.innerHTML='<option value="">All</option>'+[...new Set((data.rows||[]).map(r=>r[k]||''))].sort().map(v=>'<option value="'+esc(v||'__blank')+'">'+esc(v||'(Blank)')+'</option>').join('');s.value=selected}render()}catch(e){host.querySelector('.handover-message').textContent='Could not refresh handover status: '+e.message}finally{busy=false;b.disabled=false}}
let timer;host.addEventListener('input',e=>{if(e.target.matches('[data-package]')){clearTimeout(timer);timer=setTimeout(render,120)}});host.addEventListener('change',render);host.querySelector('[data-clear]').onclick=()=>{host.querySelectorAll('input,select').forEach(e=>e.value='');selectedSubsystem='';picker.open=false;drawSubsystemOptions();drawPackageOptions();render()};host.querySelector('[data-refresh]').onclick=load;document.addEventListener('punch-updated',()=>{if(active)void load()});
window.HandoverStatus={activate(on){active=on;host.hidden=!on;if(!on)picker.open=false;if(on){render();void load()}},summarize};
})();
