(function(){
'use strict';
document.body.classList.add('operations','operations-full');
let full=true,mode=document.querySelector('.mode-tabs [data-mode].selected')?.dataset.mode||'punch',pending=false,bar=null;
const drawer=document.createElement('dialog');drawer.id='workspaceSidebar';drawer.setAttribute('aria-label','Workspace menu');drawer.innerHTML='<header><div class="sidebar-brand">▱ <span>TOP<small>Field Operations</small></span></div><button class="sidebar-close" aria-label="Close sidebar">×</button></header><div class="sidebar-project"><small>CURRENT PROJECT</small><strong>CHP Dradenau</strong><span>Hamburg</span></div><nav class="sidebar-navigation" aria-label="Workspace"></nav><div class="sidebar-label">MANAGEMENT</div><div class="sidebar-management"></div><div class="sidebar-label">APPEARANCE</div><button id="workspaceTheme" aria-pressed="false">Dark mode <span>Off</span></button><footer><strong class="sidebar-user"></strong><small>Project workspace</small></footer>';document.body.append(drawer);
let opener;function closeDrawer(){drawer.close();opener?.focus({preventScroll:true})}drawer.querySelector('.sidebar-close').onclick=closeDrawer;drawer.addEventListener('click',e=>{if(e.target!==drawer)return;const r=drawer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDrawer()});
const theme=drawer.querySelector('#workspaceTheme');function paintTheme(){const dark=document.documentElement.dataset.theme==='dark';theme.setAttribute('aria-pressed',String(dark));theme.querySelector('span').textContent=dark?'On':'Off'}paintTheme();theme.onclick=()=>{const value=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=value;try{localStorage.setItem('top-workspace-theme',value)}catch{}paintTheme()};
function setup(){bar=document.querySelector('.access-bar');if(!bar)return;bar.classList.add('workspace-header');const tabs=document.querySelector('.mode-tabs');if(tabs&&tabs.parentElement!==bar){tabs.setAttribute('aria-label','Workspace sections');bar.prepend(tabs)}
 if(!bar.querySelector('#workspaceMenu')){opener=document.createElement('button');opener.id='workspaceMenu';opener.textContent='☰';opener.setAttribute('aria-label','Open sidebar');opener.setAttribute('aria-controls','workspaceSidebar');opener.onclick=()=>{drawer.showModal();drawer.querySelector('.sidebar-close').focus()};bar.prepend(opener)}
 const management=drawer.querySelector('.sidebar-management');for(const id of ['accessUsers','punchStorage','accessLogout']){const b=document.getElementById(id);if(b&&b.parentElement!==management){management.append(b);b.addEventListener('click',()=>drawer.close(),{capture:true})}}
 const name=bar.querySelector('.access-profile')?.textContent||'';if(drawer.querySelector('.sidebar-user').textContent!==name)drawer.querySelector('.sidebar-user').textContent=name;
 for(const b of bar.querySelectorAll('.mode-tabs button:not([data-mode])'))management.append(b);
 if(!drawer.querySelector('[data-section]'))for(const source of bar.querySelectorAll('[data-mode]')){const b=document.createElement('button');b.textContent=source.textContent;b.dataset.section=source.dataset.mode;b.onclick=()=>{closeDrawer();source.click()};drawer.querySelector('nav').append(b)}
}
function applyFull(){document.body.classList.toggle('operations-full',full);if(mode==='punch')window.PunchBrowser?.setExpanded(full);if(mode==='cables')window.CableRegister?.setExpanded(full)}
function layout(){pending=false;setup();if(bar)document.documentElement.style.setProperty('--access-bar-height',Math.ceil(bar.getBoundingClientRect().height)+'px');
 for(const [panelId,selector] of [['punchPanel','#punchExpand'],['cablePanel','[data-expand]']]){const panel=document.getElementById(panelId),button=panel?.querySelector(selector),footer=panel?.querySelector('.punch-footer');if(button&&footer&&button.parentElement!==footer)footer.append(button)}
 for(const b of drawer.querySelectorAll('[data-section]'))b.classList.toggle('selected',b.dataset.section===mode);
 const menu=document.querySelector('.cable-column-menu');if(menu&&!menu.querySelector('.menu-close')){const close=document.createElement('button');close.type='button';close.className='action menu-close';close.textContent='Close ×';close.onclick=()=>{menu.open=false;menu.querySelector('summary').focus()};menu.querySelector('[data-columns]').prepend(close)}
 for(const p of document.querySelectorAll('#punchPanel:not(.punch-expanded),#cablePanel:not(.cable-fullscreen)')){if(p.hidden)continue;const s=p.querySelector('.punch-scroll');if(s){const v=Math.max(220,innerHeight-s.getBoundingClientRect().top-80)+'px';if(p.style.getPropertyValue('--workspace-height')!==v)p.style.setProperty('--workspace-height',v)}}
}
function schedule(){if(!pending){pending=true;requestAnimationFrame(layout)}}
document.addEventListener('workspace-mode-changed',e=>{mode=e.detail.mode;applyFull();schedule()});
document.addEventListener('click',e=>{if(e.target.closest('#punchExpand,#cablePanel [data-expand]')){full=!e.target.closest('.punch-expanded,.cable-fullscreen');document.body.classList.toggle('operations-full',full)}schedule()},true);
new MutationObserver(records=>{if(records.every(r=>r.target.closest?.('tbody,.punch-mobile-cards')))return;schedule()}).observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',schedule);document.addEventListener('punch-updated',schedule);
function closeMenus(target){for(const d of document.querySelectorAll('.cable-column-menu[open]'))if(!d.contains(target))d.open=false}
document.addEventListener('pointerdown',e=>{closeMenus(e.target);const d=e.target;if(d instanceof HTMLDialogElement&&d.open&&d.matches('.columns-dialog,.workspace-dialog')){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenus(null)});
ProjectAccess.ready.then(()=>{setup();applyFull();schedule()});schedule();
})();
