(function(){
'use strict';
const API='https://drawing-finder-ocr-api-639231007303.europe-west1.run.app',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s||'').toUpperCase().replace(/\s/g,'').replace(/[•·]/g,':');
let comments=new Map(),photos=new Map(),progress=new Map(),photoEnabled=false,commentReady=false,photoReady=false,progressReady=false,loading=null;
const keys=new Map(),hashes=new Map(),encoder=new TextEncoder();let cableCache=new WeakMap();
function rowId(row){return JSON.stringify([row.sheet||'Punch',String(row.itemNumber)])}
async function key(row){const id=rowId(row);if(keys.has(id))return keys.get(id);if(!hashes.has(id))hashes.set(id,crypto.subtle.digest('SHA-256',encoder.encode(id)).then(b=>{const h=[...new Uint8Array(b)].map(n=>n.toString(16).padStart(2,'0')).join('');keys.set(id,h);hashes.delete(id);return h}));return hashes.get(id)}
function notify(){document.dispatchEvent(new Event('punch-extras-updated'))}
async function prepareKeys(){const rows=PunchItems.getSnapshot()?.rows||[];for(let i=0;i<rows.length;i+=256)await Promise.all(rows.slice(i,i+256).map(key));notify()}
async function refresh(){if(loading)return loading;loading=(async()=>{const requests=[['comments','/api/punch-comments/summary'],['photos','/api/punch-photos/summary'],['progress','/api/cables/progress']];await Promise.allSettled(requests.map(async([kind,path])=>{try{const d=await ProjectAccess.api(path);if(kind==='comments'){comments=new Map(d.rows.map(r=>[r.key,r.latest]));commentReady=true}else if(kind==='photos'){photos=new Map(d.rows.map(r=>[r.key,r]));photoEnabled=d.enabled;photoReady=true}else{progress=new Map(d.rows.map(r=>[norm(r.cable),r]));progressReady=true;cableCache=new WeakMap()}}catch(e){console.warn('Punch '+kind+' unavailable:',e.message);if(kind==='comments'&&!commentReady)commentReady='error';if(kind==='photos'&&!photoReady)photoReady='error';if(kind==='progress'&&!progressReady)progressReady='error'}}));await prepareKeys()})().finally(()=>loading=null);return loading}
function latest(row){return comments.get(keys.get(rowId(row)))}
function photo(row){return photos.get(keys.get(rowId(row)))}
function cableState(row){if(!progressReady)return 'Loading…';if(progressReady==='error')return 'Unavailable';if(cableCache.has(row))return cableCache.get(row);const text=[row.locationRoom,row.description].join(' ').toUpperCase().replace(/[•·]/g,':');const ids=[...new Set((text.match(/[A-Z0-9]+(?:[:/_.-][A-Z0-9]+)*/g)||[]).map(norm).filter(v=>progress.has(v)||/^\d{2}[A-Z]{3}\d{2}:\d{3,6}[A-Z]?$/.test(v)))];let state='No cable reference';if(ids.length){const found=ids.map(id=>progress.get(id));state=found.every(x=>x?.state==='Both side termination completed')?'Both side termination completed':found.some(x=>!x||x.state==='No date')?'No date':'Dates incomplete'}cableCache.set(row,state);return state}
function value(row,column){if(column==='latestComment'){const c=latest(row);return c?c.text:commentReady==='error'?'Unavailable':commentReady?'':'Loading…'}if(column==='cableCompletion')return cableState(row);if(column==='photoCount')return photoReady?photo(row)?.count||0:'Loading…';return ''}
function cell(row,column,index){if(column==='latestComment'){const c=latest(row);return c?'<button class="punch-comment-preview" data-comment-preview="'+index+'"><span>'+esc(c.text)+'</span><small>'+esc(c.authorName)+' · '+esc(PunchItems.formatObserved(new Date(c.createdAt).toISOString()))+'</small></button>':'<span class="hint">'+(commentReady==='error'?'Unavailable':commentReady?'—':'Loading…')+'</span>'}if(column==='photoCount'){const p=photo(row);return p?'<button class="punch-photo-trigger" data-photo-preview="'+index+'" aria-label="Preview '+p.count+' photos">▧ '+p.count+'</button>':'<span class="hint">'+(photoReady==='error'?'Unavailable':photoReady?'—':'Loading…')+'</span>'}if(column==='cableCompletion'){const state=cableState(row);return '<span class="cable-completion '+(state==='Both side termination completed'?'is-complete':'')+'">'+esc(state)+'</span>'}return null}
const tip=document.createElement('div');tip.className='punch-preview-popover';tip.hidden=true;tip.setAttribute('role','dialog');document.body.append(tip);let hoverTimer=null,tipRun=0,anchor=null;
function hide(){clearTimeout(hoverTimer);tipRun++;tip.hidden=true;tip.replaceChildren();anchor=null}
function position(button){const r=button.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.left,innerWidth-390))+'px';tip.style.top=Math.max(8,Math.min(r.bottom+5,innerHeight-350))+'px'}
async function history(row,button){const run=++tipRun;anchor=button;tip.innerHTML='<strong>Comment history</strong><div class="preview-content">Loading…</div><button class="action" data-preview-close>Close</button>';position(button);tip.hidden=false;const list=tip.querySelector('.preview-content');let cursor=null;async function load(){try{const d=await ProjectAccess.api('/api/punch-comments?'+new URLSearchParams({sheet:row.sheet||'Punch',item:row.itemNumber,...(cursor?{after:cursor}:{})}));if(run!==tipRun)return;if(!cursor)list.replaceChildren();for(const c of d.comments){const a=document.createElement('article');a.innerHTML='<small>'+esc(c.authorName)+' · '+esc(PunchItems.formatObserved(new Date(c.createdAt).toISOString()))+'</small><p>'+esc(c.text)+'</p>';list.append(a)}cursor=d.next;tip.querySelector('[data-older]')?.remove();if(cursor){const b=document.createElement('button');b.dataset.older='1';b.className='action';b.textContent='Older comments';b.onclick=load;tip.append(b)}}catch(e){if(run===tipRun)list.textContent=e.message}}await load()}
const blobs=new Map();
async function imageUrl(id,size='thumb'){const k=id+size;if(blobs.has(k)){const v=blobs.get(k);blobs.delete(k);blobs.set(k,v);return v}const response=await fetch(API+'/api/punch-photos/image?'+new URLSearchParams({id,size}));if(!response.ok)throw Error('Photo could not be loaded.');const url=URL.createObjectURL(await response.blob());blobs.set(k,url);while(blobs.size>50){const [old,u]=blobs.entries().next().value;URL.revokeObjectURL(u);blobs.delete(old)}return url}
async function previewPhoto(row,button){const run=++tipRun;anchor=button;tip.innerHTML='<strong>Photo preview</strong><div class="preview-content">Loading…</div><button class="action" data-preview-close>Close</button>';position(button);tip.hidden=false;try{const p=photo(row),url=await imageUrl(p.coverId);if(run!==tipRun)return;tip.querySelector('.preview-content').innerHTML='<img src="'+url+'" alt="Punch '+esc(row.itemNumber)+' photo"><small>'+p.count+' photo(s). Open the punch to view all.</small>'}catch(e){if(run===tipRun)tip.querySelector('.preview-content').textContent=e.message}}
function schedule(button){clearTimeout(hoverTimer);const index=button.dataset.commentPreview??button.dataset.photoPreview,row=PunchItems.getSnapshot()?.rows[Number(index)];if(!row)return;hoverTimer=setTimeout(()=>button.isConnected&&(button.hasAttribute('data-comment-preview')?history(row,button):previewPhoto(row,button)),button.hasAttribute('data-comment-preview')?1500:350)}
document.addEventListener('pointerover',e=>{const b=e.target.closest('[data-comment-preview],[data-photo-preview]');if(b&&!b.contains(e.relatedTarget))schedule(b)});
document.addEventListener('pointerout',e=>{const b=e.target.closest('[data-comment-preview],[data-photo-preview]');if(b&&!b.contains(e.relatedTarget)){clearTimeout(hoverTimer);if(!tip.contains(e.relatedTarget))setTimeout(()=>{if(!tip.matches(':hover')&&!anchor?.matches(':hover'))hide()},180)}});
document.addEventListener('focusin',e=>{const b=e.target.closest('[data-comment-preview],[data-photo-preview]');if(b)schedule(b)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-comment-preview],[data-photo-preview]');if(b){clearTimeout(hoverTimer);const row=PunchItems.getSnapshot()?.rows[Number(b.dataset.commentPreview??b.dataset.photoPreview)];if(row)b.hasAttribute('data-comment-preview')?history(row,b):previewPhoto(row,b)}else if(e.target.closest('[data-preview-close]'))hide()});
tip.addEventListener('pointerleave',hide);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!tip.hidden){e.preventDefault();e.stopImmediatePropagation();hide()}},true);window.addEventListener('resize',hide);document.addEventListener('scroll',e=>{if(!tip.contains(e.target))hide()},true);
function photoSection(target,row){const section=document.createElement('section');section.className='punch-photos';section.innerHTML='<h3>Photos</h3><div class="punch-photo-grid"></div><p class="photo-status" role="status">Loading…</p>';target.append(section);target.closest('dialog')?.addEventListener('close',()=>section.remove(),{once:true});const grid=section.querySelector('.punch-photo-grid'),status=section.querySelector('.photo-status');let alive=()=>section.isConnected;
 async function load(){try{const d=await ProjectAccess.api('/api/punch-photos?key='+await key(row));if(!alive())return;photoEnabled=d.enabled;grid.replaceChildren();status.textContent=d.rows.length?'':d.enabled?'No photos yet.':'Photo storage setup is required.';const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){observer.unobserve(e.target);imageUrl(e.target.dataset.photoId).then(url=>{if(alive())e.target.insertAdjacentHTML('afterbegin','<img src="'+url+'" alt="Punch photo">')}).catch(()=>{})}},{rootMargin:'100px'});target.closest('dialog')?.addEventListener('close',()=>observer.disconnect(),{once:true});for(const p of d.rows){const button=document.createElement('button');button.className='photo-card';button.innerHTML='<span>'+esc(p.name)+'</span>';grid.append(button);button.dataset.photoId=p.id;observer.observe(button);button.onclick=()=>openPhoto(p)}if(d.enabled&&['writer','admin'].includes(ProjectAccess.user?.role)&&!section.querySelector('input')){const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.multiple=true;input.setAttribute('aria-label','Upload punch photos');section.append(input);input.onchange=async()=>{input.disabled=true;try{if(input.files.length>10)throw Error('Choose at most 10 photos at a time.');for(const file of input.files){status.textContent='Uploading '+file.name+'…';await upload(row,file)}await refresh();await load()}catch(e){status.textContent=e.message}finally{input.disabled=false;input.value=''}}}}catch(e){if(alive())status.textContent=e.message}}
 load();
}
async function upload(row,file){if(file.size>15*1024*1024)throw Error('Photo exceeds 15 MB: '+file.name);const body=new FormData();body.append('file',file);return ProjectAccess.api('/api/punch-photos?'+new URLSearchParams({item:row.itemNumber,sheet:row.sheet||'Punch'}),{method:'POST',body})}
async function openPhoto(p){const dialog=document.createElement('dialog');dialog.className='photo-viewer';dialog.innerHTML='<button class="action" style="float:right">Close ×</button><h3>'+esc(p.name)+'</h3><p>Loading…</p>';document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();try{const url=await imageUrl(p.id,'display');if(dialog.open)dialog.querySelector('p').outerHTML='<img src="'+url+'" alt="'+esc(p.name)+'">'}catch(e){if(dialog.open)dialog.querySelector('p').textContent=e.message}}
function bulkUpload(){const dialog=document.createElement('dialog');dialog.className='photo-import';dialog.innerHTML='<button class="action photo-close" style="float:right">Close ×</button><h2>Import punch photos</h2><p>Keep existing NFI + Walkdown Item filenames, or use a punch number (e.g. 7632-1.jpg). Unmatched or ambiguous files are never uploaded automatically.</p><input type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="photo-import-list"></div><button class="action photo-upload" disabled>Upload matched photos</button><p class="photo-message" role="status"></p>';document.body.append(dialog);dialog.showModal();const close=()=>dialog.close();dialog.querySelector('.photo-close').onclick=close;dialog.addEventListener('close',()=>dialog.remove());const input=dialog.querySelector('input'),button=dialog.querySelector('.photo-upload'),message=dialog.querySelector('.photo-message');let jobs=[],running=false;
 dialog.addEventListener('cancel',e=>{if(running)e.preventDefault()});input.onchange=()=>{jobs=[];const match=PhotoMatching.createMatcher(PunchItems.getSnapshot()?.rows||[]);if(input.files.length>100){message.textContent='Choose at most 100 photos per batch.';button.disabled=true;return}for(const file of input.files){const found=match(file.name);jobs.push({file,row:found.length===1?found[0]:null,state:found.length===1?'Punch '+found[0].itemNumber:found.length?'Ambiguous — skipped':'No match — skipped'})}paint();button.disabled=!jobs.some(j=>j.row);message.textContent='Review matches, then upload.'};function paint(){dialog.querySelector('.photo-import-list').innerHTML=jobs.map(j=>'<p>'+esc(j.file.name)+' → '+esc(j.state)+'</p>').join('')}
 button.onclick=async()=>{running=true;button.disabled=true;input.disabled=true;dialog.querySelector('.photo-close').disabled=true;for(const j of jobs.filter(j=>j.row&&!j.done)){try{message.textContent='Uploading '+j.file.name;await upload(j.row,j.file);j.done=true;j.state='Uploaded → Punch '+j.row.itemNumber}catch(e){j.state='Failed: '+e.message}paint()}await refresh();message.textContent=jobs.filter(j=>j.done).length+' photos uploaded. Unmatched files were skipped.';running=false;button.disabled=!jobs.some(j=>j.row&&!j.done);input.disabled=false;dialog.querySelector('.photo-close').disabled=false};
}
document.addEventListener('punch-updated',()=>prepareKeys().catch(()=>{}));ProjectAccess.ready.then(()=>{refresh();setInterval(refresh,60000)});
window.PunchExtras={value,cell,photoSection,bulkUpload,refresh,async commentSaved(row,c){comments.set(await key(row),c);commentReady=true;notify()},key,cableState};
})();
